### ISSUE TITLE
Undefined macros generate warnings when not defined by the user

### ISSUE THREAD

**Issue by vincent-chtln** [STMicroelectronics/lsm6dsv16b-pid#1]
Compiling the library using GCC with the `-Wundef` flag generates several warnings for `NPY_HALF_GENERATE_OVERFLOW`, `NPY_HALF_GENERATE_UNDERFLOW` and `NPY_HALF_ROUND_TIES_TO_EVEN` (file `lsm6dsv16b_reg.c`, line 6200~6300).

Would it be possible to set these to a default value in the .c or .h file, like in the sample below ? Maybe 0 would probably be the best, as this is the default behavior when a macro isn't defined. 

```c
#ifndef NPY_HALF_GENERATE_OVERFLOW
#define NPY_HALF_GENERATE_OVERFLOW 0
#endif
```

This would prevent showing useless warnings to the user about something he probably doesn't care (without defining himself the macros in the build script), and would still let advanced users tweak it as they want.

**Comment by vincent-chtln** [comment]
Hi @avisconti, sorry if you're not the appropriate person, but I didn't receive any answer and you're the last person who made a commit in this repo.
Would you consider a PR to fix this ? Or maybe this is something you have already fixed internally and it will be available in the next release ?

**Comment by avisconti** [comment]
> Hi @avisconti, sorry if you're not the appropriate person, but I didn't receive any answer and you're the last person who made a commit in this repo. Would you consider a PR to fix this ? Or maybe this is something you have already fixed internally and it will be available in the next release ?

Yes, I'm the right person. Sorry, but I missed it... I'll take a look at it asap

**Comment by avisconti** [comment]
> Compiling the library using GCC with the `-Wundef` flag generates several warnings for `NPY_HALF_GENERATE_OVERFLOW`, `NPY_HALF_GENERATE_UNDERFLOW` and `NPY_HALF_ROUND_TIES_TO_EVEN` (file `lsm6dsv16b_reg.c`, line 6200~6300).
> 
> Would it be possible to set these to a default value in the .c or .h file, like in the sample below ? Maybe 0 would probably be the best, as this is the default behavior when a macro isn't defined.
> 
> ```c
> #ifndef NPY_HALF_GENERATE_OVERFLOW
> #define NPY_HALF_GENERATE_OVERFLOW 0
> #endif
> ```
> 
> This would prevent showing useless warnings to the user about something he probably doesn't care (without defining himself the macros in the build script), and would still let advanced users tweak it as they want.

I think your proposal can be accepted, as it seems the best solution. I could also remove completely the ifdefs part, but I would prepfer to keep the ```npy_floatbits_to_halfbits()``` and the ```npy_float_to_half()``` routines as they are, since they are copied from  https://github.com/numpy/numpy.

**Comment by avisconti** [comment]
Actually, I guess i can define as following:

```
#define NPY_HALF_GENERATE_OVERFLOW  0 /* do not trigger FP overflow */
#define NPY_HALF_GENERATE_UNDERFLOW 0 /* do not trigger FP underflow */
#define NPY_HALF_ROUND_TIES_TO_EVEN 1
```

This because, everything is handled inside, and my impementation does not implement the FP overflow/underflow. I enabled the round ties to even though... Tomorrow I'll do some testing

**Comment by vincent-chtln** [comment]
> Yes, I'm the right person. Sorry, but I missed it... I'll take a look at it asap

No problem, it happens !

> Actually, I guess i can define as following:
> 
> ```
> #define NPY_HALF_GENERATE_OVERFLOW  0 /* do not trigger FP overflow */
> #define NPY_HALF_GENERATE_UNDERFLOW 0 /* do not trigger FP underflow */
> #define NPY_HALF_ROUND_TIES_TO_EVEN 1
> ```
> 
> This because, everything is handled inside, and my impementation does not implement the FP overflow/underflow. I enabled the round ties to even though... Tomorrow I'll do some testing

Agreed on `NPY_HALF_GENERATE_OVERFLOW` and `NPY_HALF_GENERATE_UNDERFLOW`, since `npy_set_floatstatus_overflow()` and `npy_set_floatstatus_underflow()` are not defined in the driver, it's probably better to always set them to 0 instead of letting the possibility for an invalid config which fails the compilation.

About `NPY_HALF_ROUND_TIES_TO_EVEN`, it seems both values are valid but produces a different rounding result (although I'm not expert in that space, so better wait for the result of your tests). It is possible some user-application rely on `NPY_HALF_ROUND_TIES_TO_EVEN` being 0 or 1 when they call `lsm6dsv16b_sflp_game_gbias_set()`, so always setting it to an specific value might disturb or break some edge cases.
If the tests shows a different behavior for both values, would it better to go with the `#ifndef` method or always set it to 0/1 ? In case of the later, maybe increment major release to 3 to reflect a potential breaking change ?

**Comment by avisconti** [comment]
> > Yes, I'm the right person. Sorry, but I missed it... I'll take a look at it asap
> 
> No problem, it happens !
> 
> > Actually, I guess i can define as following:
> > ```
> > #define NPY_HALF_GENERATE_OVERFLOW  0 /* do not trigger FP overflow */
> > #define NPY_HALF_GENERATE_UNDERFLOW 0 /* do not trigger FP underflow */
> > #define NPY_HALF_ROUND_TIES_TO_EVEN 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This because, everything is handled inside, and my impementation does not implement the FP overflow/underflow. I enabled the round ties to even though... Tomorrow I'll do some testing
> 
> Agreed on `NPY_HALF_GENERATE_OVERFLOW` and `NPY_HALF_GENERATE_UNDERFLOW`, since `npy_set_floatstatus_overflow()` and `npy_set_floatstatus_underflow()` are not defined in the driver, it's probably better to always set them to 0 instead of letting the possibility for an invalid config which fails the compilation.
> 

Yes, exactly.

> About `NPY_HALF_ROUND_TIES_TO_EVEN`, it seems both values are valid but produces a different rounding result (although I'm not expert in that space, so better wait for the result of your tests). It is possible some user-application rely on `NPY_HALF_ROUND_TIES_TO_EVEN` being 0 or 1 when they call `lsm6dsv16b_sflp_game_gbias_set()`, so always setting it to an specific value might disturb or break some edge cases. If the tests shows a different behavior for both values, would it better to go with the `#ifndef` method or always set it to 0/1 ? In case of the later, maybe increment major release to 3 to reflect a potential breaking change ?

I tend to believe you are right. The application using this APIs may want to configure differently the NPY_HALF_ROUND_TIES_TO_EVEN, so I would go with:

```
#ifndef NPY_HALF_ROUND_TIES_TO_EVEN
#define NPY_HALF_ROUND_TIES_TO_EVEN 1
#endif
```

Here, I would prefer to set it to '1', just because yesterday I noticed that is the default case for the npy library. Anyway, it doesn't seem to me that the two cases have appreciable differences.

Finally. yes, I would go with v3.0.0.
Thanks

**Comment by avisconti** [comment]
Ah! I'm making same modification in all following drivers:

ism330bx
lsm6dsv16b
lsm6dsv16bx
st1vafe6ax
lsm6dsv16x
lsm6dsv32x
lsm6dsv

**Comment by vincent-chtln** [comment]
> Ah! I'm making same modification in all following drivers:
> 
> ism330bx
> lsm6dsv16b
> lsm6dsv16bx
> st1vafe6ax
> lsm6dsv16x
> lsm6dsv32x
> lsm6dsv

Great ! Thanks a lot for the quick support. 😄 These drivers really quickens development process, especially for more complex sensors like IMU.

Feel free to close this issue whenever you think it's appropriate, I'll move to v3.0.0 when released.
